SELECT TO_CHAR(NORPAC.DEBRIEFED_LENGTH_MV.PORT_JOIN)
AS PORT_JOIN
FROM NORPAC.DEBRIEFED_LENGTH_MV
WHERE NORPAC.DEBRIEFED_LENGTH_MV.FMP_AREA
          -- insert region
AND NORPAC.DEBRIEFED_LENGTH_MV.SPECIES
          -- insert species
