SELECT TO_CHAR(NORPAC.DEBRIEFED_AGE_MV.HAUL_JOIN)
       AS HAUL_JOIN
       FROM NORPAC.DEBRIEFED_AGE_MV
       WHERE NORPAC.DEBRIEFED_AGE_MV.FMP_AREA
       -- insert region
       AND NORPAC.DEBRIEFED_AGE_MV.SPECIES
       -- insert species
