
SELECT COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR,
         COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_NAME,
         COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE,
         COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR,
         COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_AREA,
         COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_SUBAREA,
         COUNCIL.COMPREHENSIVE_BLEND_CA.WEEK_END_DATE,
         COUNCIL.COMPREHENSIVE_BLEND_CA.WEIGHT_POSTED
         FROM COUNCIL.COMPREHENSIVE_BLEND_CA
         WHERE COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_AREA
         -- insert region
         AND COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR
         -- insert year
                AND COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE
                -- insert species
