SELECT NORPAC.DEBRIEFED_AGE_MV.YEAR,
NORPAC.DEBRIEFED_AGE_MV.FMP_AREA,
NORPAC.DEBRIEFED_AGE_MV.SPECIES,
NORPAC.DEBRIEFED_AGE_MV.LENGTH,
NORPAC.DEBRIEFED_AGE_MV.WEIGHT,
NORPAC.DEBRIEFED_AGE_MV.AGE,
NORPAC.DEBRIEFED_AGE_MV.SPECIMEN_TYPE,
NORPAC.DEBRIEFED_AGE_MV.PERFORMANCE
FROM NORPAC.DEBRIEFED_AGE_MV
WHERE NORPAC.DEBRIEFED_AGE_MV.FMP_AREA
        -- insert region
AND NORPAC.DEBRIEFED_AGE_MV.SPECIES
        -- insert species
