SELECT TO_CHAR(NORPAC.DEBRIEFED_LENGTH_MV.HAUL_JOIN)
AS HAUL_JOIN
FROM NORPAC.DEBRIEFED_LENGTH_MV
WHERE NORPAC.DEBRIEFED_LENGTH_MV.FMP_AREA
          -- insert region
AND NORPAC.DEBRIEFED_LENGTH_MV.SPECIES
          -- insert species
