SELECT TO_CHAR(NORPAC.DEBRIEFED_AGE_MV.PORT_JOIN)
       AS PORT_JOIN
       FROM NORPAC.DEBRIEFED_AGE_MV
       WHERE NORPAC.DEBRIEFED_AGE_MV.FMP_AREA
       -- insert region
       AND NORPAC.DEBRIEFED_AGE_MV.SPECIES
       -- insert species
