SELECT NORPAC.DEBRIEFED_SPCOMP_MV.YEAR,
NORPAC.DEBRIEFED_SPCOMP_MV.HAUL_DATE,
NORPAC.DEBRIEFED_SPCOMP_MV.SPECIES,
NORPAC.DEBRIEFED_HAUL_MV.FMP_AREA,
NORPAC.DEBRIEFED_HAUL_MV.GEAR_TYPE,
NORPAC.DEBRIEFED_SPCOMP_MV.EXTRAPOLATED_WEIGHT
FROM NORPAC.DEBRIEFED_SPCOMP_MV
INNER JOIN NORPAC.DEBRIEFED_HAUL_MV
ON NORPAC.DEBRIEFED_SPCOMP_MV.JOIN_KEY = NORPAC.DEBRIEFED_HAUL_MV.JOIN_KEY
WHERE NORPAC.DEBRIEFED_SPCOMP_MV.YEAR
BETWEEN
-- insert year
AND
-- year2
AND NORPAC.DEBRIEFED_HAUL_MV.FMP_AREA
-- insert region
AND NORPAC.DEBRIEFED_SPCOMP_MV.SPECIES
-- insert species
