SELECT RACEBASE.LENGTH.CRUISEJOIN,
RACEBASE.LENGTH.REGION,
RACEBASE.LENGTH.SPECIES_CODE,
RACEBASE.LENGTH.LENGTH,
RACEBASE.LENGTH.FREQUENCY,
GOA.BIENNIAL_SURVEYS.YEAR,
RACEBASE.HAUL.PERFORMANCE,
RACEBASE.HAUL.HAULJOIN
FROM (RACEBASE.HAUL INNER JOIN RACEBASE.LENGTH
ON RACEBASE.HAUL.HAULJOIN = RACEBASE.LENGTH.HAULJOIN)
INNER JOIN GOA.BIENNIAL_SURVEYS
ON RACEBASE.LENGTH.CRUISEJOIN = GOA.BIENNIAL_SURVEYS.CRUISEJOIN
WHERE (((RACEBASE.LENGTH.REGION) = 'GOA')
AND (RACEBASE.LENGTH.SPECIES_CODE)
-- insert species
AND (RACEBASE.HAUL.PERFORMANCE)>=0)
