SELECT GOA.SIZECOMP_TOTAL.SURVEY,
 GOA.SIZECOMP_TOTAL.YEAR,
 GOA.SIZECOMP_TOTAL.SPECIES_CODE,
 GOA.SIZECOMP_TOTAL.LENGTH,
 GOA.SIZECOMP_TOTAL.MALES,
 GOA.SIZECOMP_TOTAL.FEMALES,
 GOA.SIZECOMP_TOTAL.UNSEXED,
 GOA.SIZECOMP_TOTAL.TOTAL
 FROM GOA.SIZECOMP_TOTAL
 WHERE
GOA.SIZECOMP_TOTAL.SPECIES_CODE
        -- insert species
