SELECT GOA.SIZECOMP_DEPTH.SURVEY,
    GOA.SIZECOMP_DEPTH.SUMMARY_DEPTH,
    GOA.SIZECOMP_DEPTH.YEAR,
    GOA.SIZECOMP_DEPTH.SPECIES_CODE,
    GOA.SIZECOMP_DEPTH.LENGTH,
    GOA.SIZECOMP_DEPTH.MALES,
    GOA.SIZECOMP_DEPTH.FEMALES,
    GOA.SIZECOMP_DEPTH.UNSEXED,
    GOA.SIZECOMP_DEPTH.TOTAL
    FROM GOA.SIZECOMP_DEPTH
WHERE GOA.SIZECOMP_DEPTH.SPECIES_CODE 
-- insert species
