SELECT GOA.BIOMASS_TOTAL.SURVEY,
GOA.BIOMASS_TOTAL.YEAR,
GOA.BIOMASS_TOTAL.SPECIES_CODE,
GOA.BIOMASS_TOTAL.HAUL_COUNT,
GOA.BIOMASS_TOTAL.CATCH_COUNT,
GOA.BIOMASS_TOTAL.MEAN_WGT_CPUE,
GOA.BIOMASS_TOTAL.VAR_WGT_CPUE,
GOA.BIOMASS_TOTAL.MEAN_NUM_CPUE,
GOA.BIOMASS_TOTAL.VAR_NUM_CPUE,
GOA.BIOMASS_TOTAL.TOTAL_BIOMASS,
GOA.BIOMASS_TOTAL.BIOMASS_VAR,
GOA.BIOMASS_TOTAL.MIN_BIOMASS,
GOA.BIOMASS_TOTAL.MAX_BIOMASS,
GOA.BIOMASS_TOTAL.TOTAL_POP,
GOA.BIOMASS_TOTAL.POP_VAR
FROM GOA.BIOMASS_TOTAL
WHERE GOA.BIOMASS_TOTAL.SPECIES_CODE
-- insert species
