SELECT AFSC.WEB_AREAS.YEAR,
AFSC.WEB_AREAS.SURVEY,
AFSC.WEB_AREAS.AREA_ID,
AFSC.WEB_AREAS.AREA,
AFSC.WEB_AREAS.SPECIES_CODE,
AFSC.WEB_AREAS.COMMON_NAME,
AFSC.WEB_AREAS.CPUE,
AFSC.WEB_AREAS.RPN,
AFSC.WEB_AREAS.RPW,
AFSC.WEB_AREAS.AKFIN_LOAD_DATE
FROM AFSC.WEB_AREAS
WHERE AFSC.WEB_AREAS.SPECIES_CODE
-- insert species
