SELECT RACEBASE.LENGTH.CRUISE,
    GOA.BIENNIAL_SURVEYS.YEAR,
    RACEBASE.LENGTH.HAULJOIN,
    RACEBASE.LENGTH.CRUISEJOIN,
    RACEBASE.LENGTH.SPECIES_CODE,
    RACEBASE.LENGTH.FREQUENCY,
    RACEBASE.LENGTH.LENGTH,
    RACEBASE.LENGTH.SEX,
    RACEBASE.LENGTH.REGION,
    RACEBASE.HAUL.PERFORMANCE,
    RACEBASE.HAUL.STRATUM
    FROM RACEBASE.HAUL
    INNER JOIN RACEBASE.LENGTH
    ON RACEBASE.HAUL.HAULJOIN = RACEBASE.LENGTH.HAULJOIN
    INNER JOIN GOA.BIENNIAL_SURVEYS
    ON RACEBASE.LENGTH.CRUISEJOIN = GOA.BIENNIAL_SURVEYS.CRUISEJOIN
    WHERE RACEBASE.LENGTH.SPECIES_CODE
    -- insert species
    AND RACEBASE.LENGTH.REGION = 'GOA'
     AND RACEBASE.HAUL.PERFORMANCE >=0
