SELECT YEAR,
  COUNTRY,
  VESSEL_NUMBER,
  VESSEL_NAME,
  CRUISE_NUMBER,
  AREA_CODE,
  GEOGRAPHIC_AREA_NAME,
  COUNCIL_SABLEFISH_MGMT_AREA,
  SPECIES_CODE,
  COMMON_NAME,
  SEX,
  LENGTH,
  LENGTH_FREQUENCY,
  AKFIN_LOAD_DATE
FROM AFSC.LENGTH_FREQUENCIES
WHERE SPECIES_CODE
-- insert species
AND COUNTRY != 'Japan'
