SELECT * FROM
(RACEBASE.HAUL
INNER JOIN
RACEBASE.SPECIMEN
ON RACEBASE.HAUL.HAULJOIN = RACEBASE.SPECIMEN.HAULJOIN)
INNER JOIN GOA.BIENNIAL_SURVEYS
ON RACEBASE.SPECIMEN.CRUISEJOIN = GOA.BIENNIAL_SURVEYS.CRUISEJOIN
WHERE (RACEBASE.SPECIMEN.SPECIES_CODE
-- insert species
AND RACEBASE.SPECIMEN.REGION = 'GOA'
AND RACEBASE.HAUL.PERFORMANCE >= 0)
