SELECT GOA.AGECOMP_TOTAL.SURVEY,
GOA.AGECOMP_TOTAL.SURVEY_YEAR,
GOA.AGECOMP_TOTAL.SPECIES_CODE,
GOA.AGECOMP_TOTAL.SEX,
GOA.AGECOMP_TOTAL.AGE,
GOA.AGECOMP_TOTAL.AGEPOP,
GOA.AGECOMP_TOTAL.MEAN_LENGTH,
GOA.AGECOMP_TOTAL.STANDARD_DEVIATION
FROM GOA.AGECOMP_TOTAL
WHERE GOA.AGECOMP_TOTAL.SPECIES_CODE
-- insert species
