SELECT RACEBASE.SPECIMEN.CRUISE,
GOA.BIENNIAL_SURVEYS.YEAR,
RACEBASE.SPECIMEN.HAULJOIN,
RACEBASE.SPECIMEN.CRUISEJOIN,
RACEBASE.SPECIMEN.SPECIES_CODE,
RACEBASE.SPECIMEN.SPECIMENID,
RACEBASE.SPECIMEN.LENGTH,
RACEBASE.SPECIMEN.SEX,
RACEBASE.SPECIMEN.AGE,
RACEBASE.SPECIMEN.WEIGHT,
RACEBASE.SPECIMEN.REGION,
RACEBASE.HAUL.PERFORMANCE
FROM (RACEBASE.HAUL
INNER JOIN RACEBASE.SPECIMEN
ON RACEBASE.HAUL.HAULJOIN = RACEBASE.SPECIMEN.HAULJOIN)
INNER JOIN GOA.BIENNIAL_SURVEYS
ON RACEBASE.SPECIMEN.CRUISEJOIN = GOA.BIENNIAL_SURVEYS.CRUISEJOIN
WHERE RACEBASE.SPECIMEN.SPECIES_CODE
-- insert species
AND RACEBASE.SPECIMEN.REGION = 'GOA'
AND RACEBASE.HAUL.PERFORMANCE >= 0
