SELECT * FROM AFSC.NORPAC_CATCH_HOOK_MAMMAL_V
   WHERE AFSC.NORPAC_CATCH_HOOK_MAMMAL_V.GEAR_DESCRIPTION = 'LONGLINER'
   AND AFSC.NORPAC_CATCH_HOOK_MAMMAL_V.IFQ = 'Y'
   AND AFSC.NORPAC_CATCH_HOOK_MAMMAL_V.PERFORMANCE IN (1, 8, 10)
   AND AFSC.NORPAC_CATCH_HOOK_MAMMAL_V.YEAR >= 1995
