SELECT GOA.BIOMASS_DEPTH.SURVEY,
    GOA.BIOMASS_DEPTH.SUMMARY_DEPTH,
    GOA.BIOMASS_DEPTH.YEAR,
    GOA.BIOMASS_DEPTH.SPECIES_CODE,
    GOA.BIOMASS_DEPTH.HAUL_COUNT,
    GOA.BIOMASS_DEPTH.CATCH_COUNT,
    GOA.BIOMASS_DEPTH.MEAN_WGT_CPUE,
    GOA.BIOMASS_DEPTH.VAR_WGT_CPUE,
    GOA.BIOMASS_DEPTH.MEAN_NUM_CPUE,
    GOA.BIOMASS_DEPTH.VAR_NUM_CPUE,
    GOA.BIOMASS_DEPTH.AREA_BIOMASS,
    GOA.BIOMASS_DEPTH.BIOMASS_VAR,
    GOA.BIOMASS_DEPTH.MIN_BIOMASS,
    GOA.BIOMASS_DEPTH.MAX_BIOMASS,
    GOA.BIOMASS_DEPTH.AREA_POP,
    GOA.BIOMASS_DEPTH.POP_VAR
    FROM GOA.BIOMASS_DEPTH
    WHERE GOA.BIOMASS_DEPTH.SPECIES_CODE
    -- insert species

